# -*- coding: utf-8 -*-
"""UNI ,BI and MUTIVARIATE ANALYSIS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fbh88_vNk5IWVb_4sgI0DS1J0QR_PV70
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

file_path='/content/drive/MyDrive/MACHINE LEARNING/IRIS.csv'

df=pd.read_csv(file_path)
print(df.head())

plt.figure(figsize=(9,5))
sns.scatterplot(x=df['petal_length'],y=[0]*len(df),hue=df['species'],s=100)
plt.yticks([])
plt.xlabel("Petal Length")
plt.title("Univariate Analysis of Petal Lenght by Species")
plt.legend(title="Specie")
plt.grid(True)
plt.show()

sns.pairplot(df,hue='species',vars=['sepal_length','sepal_width','petal_length','petal_width'])
plt.show()

plt.figure(figsize=(12,6))
sns.scatterplot(data=df,x='sepal_length',y='petal_length',hue='species',s=100)
plt.xlabel("Sepal Length")
plt.ylabel("Petal Length")
plt.title("Bivariate Analysis of Sepal and Petal Length by species")
plt.legend(title="Species")
plt.grid(True)
plt.show